CREATE TABLE IF NOT EXISTS UserOverview (
 'id' INTEGER PRIMARY KEY AUTOINCREMENT,
 'Bearer Id' FLOAT DEFAULT NULL,
 'Start' DATETIME DEFAULT NULL,
 'End' DATETIME DEFAULT NULL,
 'Dur' FLOAT DEFAULT NULL,
 'IMSI' FLOAT DEFAULT NULL,
 'MSISDN/Number' FLOAT DEFAULT NULL,
 'IMEI' FLOAT DEFAULT NULL,
 'Last Location Name' TEXT DEFAULT NULL,
 'Avg RTT DL (ms)' FLOAT DEFAULT NULL,
 'Avg RTT UL (ms)' FLOAT DEFAULT NULL,
 'Avg Bearer TP DL (kbps)' FLOAT DEFAULT NULL,
 'Avg Bearer TP UL (kbps)' FLOAT DEFAULT NULL,
 'TCP DL Retrans. Vol (Bytes)' FLOAT DEFAULT NULL,
 'TCP UL Retrans. Vol (Bytes)' FLOAT DEFAULT NULL,
 'HTTP DL (Bytes)' FLOAT DEFAULT NULL,
 'HTTP UL (Bytes)' FLOAT DEFAULT NULL,
 'Activity Duration DL (ms)' FLOAT DEFAULT NULL,
 'Activity Duration UL (ms)' FLOAT DEFAULT NULL,
 'Handset Manufacturer' TEXT DEFAULT NULL,
 'Handset Type' TEXT DEFAULT NULL,
 'Social Media DL (Bytes)' FLOAT DEFAULT NULL,
 'Social Media UL (Bytes)' FLOAT DEFAULT NULL,
 'Google DL (Bytes)' FLOAT DEFAULT NULL,
 'Google UL (Bytes)' FLOAT DEFAULT NULL,
 'Email DL (Bytes)' FLOAT DEFAULT NULL,
 'Email UL (Bytes)' FLOAT DEFAULT NULL,
 'Youtube DL (Bytes)' FLOAT DEFAULT NULL,
 'Youtube UL (Bytes)' FLOAT DEFAULT NULL,
 'Netflix DL (Bytes)' FLOAT DEFAULT NULL,
 'Netflix UL (Bytes)' FLOAT DEFAULT NULL,
 'Gaming DL (Bytes)' FLOAT DEFAULT NULL,
 'Gaming UL (Bytes)' FLOAT DEFAULT NULL,
 'Other DL (Bytes)' FLOAT DEFAULT NULL,
 'Other UL (Bytes)' FLOAT DEFAULT NULL,
 'Total UL (Bytes)' FLOAT DEFAULT NULL,
 'Total DL (Bytes)' FLOAT DEFAULT NULL,
 'total_google' FLOAT DEFAULT NULL,
 'total_email' FLOAT DEFAULT NULL,
 'total_gaming' FLOAT DEFAULT NULL,
 'total_youtube' FLOAT DEFAULT NULL,
 'total_netflix' FLOAT DEFAULT NULL,
 'total_social' FLOAT DEFAULT NULL,
 'total_other' FLOAT DEFAULT NULL,
 'fixed_dur' FLOAT DEFAULT NULL,
 'fixed_activity_dur_dl' FLOAT DEFAULT NULL,
 'fixed_activity_dur_ul' FLOAT DEFAULT NULL,
 'fixed_total_ul' FLOAT DEFAULT NULL,
 'total_data' FLOAT DEFAULT NULL,
 'decile' TEXT DEFAULT NULL
);
